// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACeiZ95PehDl_oQ7-_QQrNu7XWUfaLQ8g',
    appId: '1:19652774985:web:01fec6bcd6839d2618c398',
    messagingSenderId: '19652774985',
    projectId: 'archenemy-9623a',
    authDomain: 'archenemy-9623a.firebaseapp.com',
    storageBucket: 'archenemy-9623a.firebasestorage.app',
    measurementId: 'G-TEGXKBM8FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmWAyvxw62sPVGd7zEGJtzL3Kb2ufCYM0',
    appId: '1:19652774985:android:a2e434b764240a0b18c398',
    messagingSenderId: '19652774985',
    projectId: 'archenemy-9623a',
    storageBucket: 'archenemy-9623a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsOG5sh3FOPh71Gi1pUO0rYJ8iII0hwuU',
    appId: '1:19652774985:ios:aac800f872afc53918c398',
    messagingSenderId: '19652774985',
    projectId: 'archenemy-9623a',
    storageBucket: 'archenemy-9623a.firebasestorage.app',
    iosBundleId: 'com.example.hatingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsOG5sh3FOPh71Gi1pUO0rYJ8iII0hwuU',
    appId: '1:19652774985:ios:aac800f872afc53918c398',
    messagingSenderId: '19652774985',
    projectId: 'archenemy-9623a',
    storageBucket: 'archenemy-9623a.firebasestorage.app',
    iosBundleId: 'com.example.hatingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACeiZ95PehDl_oQ7-_QQrNu7XWUfaLQ8g',
    appId: '1:19652774985:web:ac7bd1510600906c18c398',
    messagingSenderId: '19652774985',
    projectId: 'archenemy-9623a',
    authDomain: 'archenemy-9623a.firebaseapp.com',
    storageBucket: 'archenemy-9623a.firebasestorage.app',
    measurementId: 'G-08ME0MYL07',
  );
}
