name: Shuttle Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JKYBBHJDQ5JPDKYCFYDX01JJ
          working-directory: "."
          cargo-shuttle-version: "0.52.0"
          extra-args: --allow-dirty --debug
          secrets: |
            FIREBASE_AUTH_PROJECT_ID = '${{ secrets.FIREBASE_AUTH_PROJECT_ID }}'
            STORAGE_ACCESS_TOKEN = '${{STORAGE_ACCESS_TOKEN}}'
            STORAGE_ACCESS_ID = '${{secrets.STORAGE_ACCESS_ID}}'
            NEON_POSTGRES_URL = '${{secrets.NEON_POSTGRES_URL}}'
