on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.dart'
      - 'pubspec.yaml'
name: Test apk and format
jobs:
  build:
    name: Test APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.x
    - run: flutter pub get
    - run: flutter test
    - run: dart format --output=none --set-exit-if-changed .
